backend:
  name: git-gateway
  repo: miltonbolonha/blog
  branch: master
  site_domain: https://miltextos.netlify.app

media_folder: "theme/public/posts"
public_folder: ""
media_library:
  name: cloudinary
  config:
    cloud_name: dyxuhpt7j
    api_key: 338884965113117

publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: post
    label: Posts
    folder: content/posts
    label_singular: Post
    description: >
      Markdown posts.
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
          required: true,
        }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Mil Textos",
        }
      - {
          label: "Categories",
          name: "categories",
          widget: "list",
          required: true,
        }
      - { label: "Tag", name: "tag", widget: "list" }
      - {
          label: "Featured Image",
          name: "image",
          widget: image,
          required: true,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Type", name: "layout", widget: "hidden", default: "post" }

  - name: pages
    label: Pages
    label_singular: "Page"
    folder: content/pages
    create: true
    # adding a nested object will show the collection folder structure
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }
      - { label: "Type", name: "layout", widget: "hidden", default: "page" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          format: "YYYY-MM-DD HH:mm:ss",
          required: true,
        }
      - { label: "Description", name: pageDescription, widget: "string" }

  - name: settings
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Settings"
        file: "content/public/manifest.json"
        description: "General Site Settings"
        fields:
          - label: "Website Name"
            name: name
            widget: string
            required: true
          - label: "Short Name"
            name: short_name
            widget: string
            required: true
            default: Mil Textos
            hint: "short_name"
          - label: "Theme Color"
            name: theme_color
            widget: string
            required: true
            hint: "#9b00dd - Specifies the color theme used by browsers when displaying your app."
          - label: "Background Color"
            name: background_color
            widget: string
            required: true
            hint: "#00ffc1 - Background color of your application's splash screen or loading screen."
          - label: "Display"
            name: display
            widget: "select"
            required: true
            options:
              [
                "Standalone (recommended)",
                "Fullscreen",
                "Minimal-UI",
                "Browser",
              ]
          - label: "Scope"
            name: scope
            widget: string
            required: true
            hint: "https://example.com/blog - A path that defines the set of URLs that belong to your PWA"
          - label: "Start Url"
            name: start_url
            widget: string
            required: true
            hint: "home - The URL of the page that opens when users launch your app from their home screen, desktop or dock (https://example.com/blog/home)."
          - label: "Logo Image"
            label_singular: Logo
            name: logo
            allow_add: true
            allow_delete: true
            allow_multiple: true
            max: 6
            min: 2
            required: true
            hint: "favicon-16x16.png, favicon-192x192.png, favicon-256x256.png, favicon-512x512.png, logotype.png, rouded-mark.png"
            widget: "list"
            fields:
              - { label: "Image", name: src, widget: "image" }
              - {
                  label: "Type",
                  name: type,
                  widget: "select",
                  options: ["image/png", "image/jpg"],
                }
              - {
                  label: "Sizes",
                  name: sizes,
                  widget: "string",
                  hint: "16x16, 192x192, 512x512, WxH - custom",
                }
          - label: "Business Settings"
            name: business
            widget: "object"
            fields:
              - { label: "Brand Name", name: brandName, widget: "string" }
              - {
                  label: "Brand Description",
                  name: brandDescription,
                  widget: "string",
                }
              - {
                  label: "Brand Phone",
                  name: brandPhone,
                  widget: "string",
                  default: "+1",
                }
              - { label: "Brand Email", name: brandEmail, widget: "string" }
              - {
                  label: "Brand Keywords",
                  name: brandKeywords,
                  widget: "list",
                  required: false,
                }
              - {
                  label: "Feedback Subject",
                  name: feedbackSubject,
                  widget: "string",
                  default: "Message Request",
                }
              - {
                  label: "Feedback Email",
                  name: feedbackEmail,
                  widget: "string",
                  default: "general@miltextos.com",
                }
              - {
                  label: "Brand Card Image",
                  name: brandCardImage,
                  widget: "image",
                  required: true,
                  default: "cover.png",
                }
              - {
                  label: "RampJS",
                  name: rampJS,
                  widget: "boolean",
                  required: false,
                  default: false,
                }
              - {
                  label: "RampJS Segment",
                  name: rampJSsegment,
                  widget: "string",
                  required: false,
                }
              - {
                  label: "Ads Client ID",
                  name: adClient,
                  widget: "string",
                  default: "ca-pub-",
                  hint: "ca-pub-",
                  required: false,
                }
              - {
                  label: "Google Analytics ID",
                  name: gaID,
                  widget: "string",
                  default: "G-",
                  required: false,
                  hint: "G-",
                }
          - label: "Website Settings"
            name: website
            widget: "object"
            fields:
              - { label: "Site Url", name: siteUrl, widget: "string" }
              - {
                  label: "Publish Date",
                  name: "date",
                  widget: "datetime",
                  format: "YYYY-MM-DD HH:mm:ss",
                }
              - {
                  label: "Footer Message",
                  name: footerMessage,
                  widget: "string",
                  default: "Disclaimer: The content provided on this site is intended for general information purposes only and should not be considered a replacement for professional financial and/or medical advice. All materials, including text, graphics, images, and information, are subject to change without prior notice. The information, materials, terms, conditions, and descriptions presented on these pages are subject to change without prior notice.",
                }
              - {
                  label: "Success Message",
                  name: successMessage,
                  widget: "string",
                  default: "Thank you for your message. We will reach you soon.",
                }
              - {
                  label: "Error Message",
                  name: errorMessage,
                  widget: "string",
                  default: "Hmm... something is wrong, try again later or e-mail us: general@miltextoss.com",
                }
          - label: "Link Tree"
            label_singular: Item
            name: linkTree
            allow_add: true
            allow_delete: true
            allow_multiple: true
            max: 6
            min: 1
            widget: "list"
            fields:
              - { label: "Label", name: label, widget: "string" }
              - { label: "Href", name: href, widget: "string" }
          - label: "Main Menu"
            label_singular: Item
            name: mainMenu
            allow_add: true
            allow_delete: true
            allow_multiple: true
            max: 6
            min: 1
            widget: "list"
            fields:
              - { label: "Label", name: label, widget: "string" }
              - { label: "Href", name: href, widget: "string" }
